includes:
  - env_variables.yaml

entrypoint: bundle exec rackup -p 8080
env: standard
runtime: ruby25

instance_class: F1

automatic_scaling:
  max_instances: 1
  min_instances: 1
  max_idle_instances: 0
  min_idle_instances: 0
