version: '3.6'
services:
  web:
    build: .
    environment:
      APP_ENV: production
    volumes:
      - ./src:/app/src
    ports:
      - "127.0.0.1:3000:3000"
    command: ruby /app/src/app.rb

