version: '3.6'
services:
  web:
    build: .
    environment:
      APP_ENV: development
      API_URL: https://chita.cl/api/v1/pricing/simple_quote
      API_KEY: UVG5jbLZxqVtsXX4nCJYKwtt
    volumes:
      - ./:/app
    ports:
      - "127.0.0.1:3000:3000"
    command: bundle exec rackup -p 3000 --host 0.0.0.0
    
